config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
      resources :users, only: [:index]
      resources :submissions, only: [:index]
      root to: "users#index"
    end
  end

  resources :communities do
    resource :subscriptions
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", :as =>
  "comment_unsubscribe"

  get :search, controller: "application"
  
  resources :submissions do
    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end
    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end
  
  devise_for :users
  resources :users, only: [:show], as: "profiles", path: "profile"
  resources :premium

  root to: "submissions#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  include VotesCountable

  belongs_to :submission
  belongs_to :user

  validates :reply, presence: true

  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy, :upvote, :downvote]
  before_action :set_submission
  before_action :find_comment, only: [:upvote, :downvote]

  def show
  end

  def new
  end
  
  def create
    @comment = @submission.comments.create(params[:comment].permit(:reply, :submission_id))
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        SubmissionMailer.with(comment: @comment, submission: @submission).new_response.deliver_later
        format.html { redirect_to submission_path(@submission) }
        format.js # renders create.js.erb in app/views/comments/
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to submission_path(@submission), notice: "Your comment did not save. Please try again."}
        format.js
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js # render edit.js.erb
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to submission_path(@submission), noticed: "Comment was successfully updated." }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to submission_path(@submission)
  end

  def upvote
    respond_to do |format|
      unless current_user.voted_for? @comment
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_head }
        format.js { flash.now[:notice] = "Successfully upvoted comment" }
        @comment.upvote_by current_user
      else
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "You already voted for this comment" }
      end
    end
  end

  def downvote
    respond_to do |format|
      unless current_user.voted_for? @comment
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_head }
        format.js { flash.now[:notice] = "Successfully down voted comment" }
        @comment.downvote_by current_user
      else
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "You already voted for this comment" }
      end
    end
  end

  private

  def set_submission
    @submission = Submission.find(params[:submission_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def find_comment
    @comment = @submission.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:reply)
  end

end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="flex items-start py-1 mt-2">
  <div class="flex flex-col items-center">
    <%= render "comments/comment_voting", comment: comment %>
  </div>
  <div class="flex-1 pl-4">
    <%= render "submissions/posted_by", submission: comment %>
    <div class="text-gray-800 leading-normal text-sm"><%= comment.reply %></div>

    <div class="my-2 flex justify-end">
      <% if author_of(comment) %>

        <%= link_to edit_submission_comment_path(comment.submission, comment), class: "no-underline mr-2", remote: true do %>
          <%= render_svg "icons/edit", styles: "fill-current text-gray-500 icon-sm hover:text-gray-600" %>
        <% end %>

        <%= link_to submission_comment_path(comment.submission, comment), method: :delete, data: { confirm: "Are your sure?" }, class: "no-underline" do %>
          <%= render_svg "icons/delete", styles: "fill-current text-gray-500 icon-sm hover:text-gray-600" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment_voting.html.erb
<% unless user_signed_in? %>
  <%= link_to new_user_session_path do %>
    <%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current text-gray-600 hover:text-purple-500" %>
  <% end %>

  <span class="text-gray-700 text-center text-sm js-votes"><%= comment.total_votes_count %></span>

  <%= link_to new_user_session_path do %>
    <%= render_svg "icons/down-vote", title: "upvote", styles: "fill-current text-gray-600 hover:text-purple-500" %>
  <% end %>
<% else %>
  <%= link_to upvote_submission_comment_path(comment.submission, comment), method: :put, remote: true do %>
    <%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current text-gray-600 hover:text-purple-500" %>
  <% end %>

  <span class="text-gray-700 text-center text-sm js-votes">
    <%= comment.total_votes_count %>
  </span>

  <%= link_to downvote_submission_comment_path(comment.submission, comment), method: :put, remote: true do %>
    <% render_svg "icons/down-vote", title: "upvote", styles: "fill-current text-gray-600 hover:text-purple-500" %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<p class="text-sm text-gray-600 my-2">comment as <%= link_to current_user.username, "#", class: "link" %></p>

<%= form_for([@submission, @comment], remote: true) do |f| %>
  <div class="relative">
    <%= f.text_area :reply, class: "input h-32 border border-gray-200 resize-none", placeholder: "What are your thoughts?" %>

    <%= f.submit class: "btn btn-small btn-purple block w-full text-center mt02 lg:mt-0 lg:text-left lg:absolute lg:bottom-0 lg:right-0 lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex" %>
  </div>
<% end %>

app/views/comments/_modal.html.erb
<h1 class="text-2xl font-normal text-gray-700">Edit comment</h1>
<%= render "form" %>

app/views/comments/_vote.js.erb
var commentVote = document.querySelector(
  "#comment-<%= @comment.id %> .js-votes"
);
var dynamicNotice = document.querySelector(".js-notice");
commentVote.innerHTML = "<%= escape_javascript(@comment.total_votes_count) %>";

dynamicNotice.innerHTML = `
  <div class="bg-white shadow rounded-lg animate fadeInUp">
    <div class="px-2 py-4 text-purple-600 text-center leading-normal font-medium font-sans flex justify-center items-center">
        <%= render_svg "icons/info", styles: "fill-current text-purple-600 icon-sm ml-4" %>
        <div class="flex-1"><%= notice %></div>
    </div>
  </div>
`;

setTimeout(function() {
  dynamicNotice.innerHTML = "";
}, 3000);

app/views/comments/comments.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById('comment_reply');
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";

app/views/comments/create.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");
comments.insertAdjacentHTML(
  "beforeend",
  "<%= escape_javascript(render(@comment)) %>"
);
commentField.value = "";

app/views/comments/downvote.js.erb
<%= render "vote" %>

app/views/comments/edit.js.erb
var editComment = document.getElementById("edit-comment");
var modalInner = document.querySelector(".modal-inner");
editComment.querySelector(".modal").classList.add("is-active");
modalInner.insertAdjacentHTML(
  "afterbegin",
  "<%= escape_javascript(render partial: 'comments/modal') %>"
);

app/views/comments/upvote.js.erb
<%= render "vote" %>