config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
      resources :users, only: [:index]
      resources :submissions, only: [:index]
      root to: "users#index"
    end
  end

  resources :communities do
    resource :subscriptions
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", :as =>
  "comment_unsubscribe"

  get :search, controller: "application"
  
  resources :submissions do
    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end
    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end
  
  devise_for :users
  resources :users, only: [:show], as: "profiles", path: "profile"
  resources :premium

  root to: "submissions#index"
end

app/models/submission.rb
class Submission < ApplicationRecord
  extend FriendlyId
  include VotesCountable

  mount_uploader :submission_image, SubmissionImageUploader
  mount_uploader :submission_video, SubmissionVideoUploader

  belongs_to :user
  belongs_to :community

  has_many  :comments, dependent: :destroy

  has_rich_text :body

  # validations
  validates :title, presence: true
  validates :url, url: { allow_blank: true }
  validate :image_or_video
  validate :url_or_content

  acts_as_votable

  friendly_id :title, use: :slugged

  private

  def image_or_video
    unless submission_image.blank? || submission_video.blank?
      unless submission_image.blank? ^ submission_video.blank?
        errors.add(:base, "Add an image or video, not both")
      end
    end
  end

  def url_or_content
    unless url.blank? || body.blank?
      unless url.blank? ^ body.blank?
        errors.add(:base, "Add a valid URL or text content")
      end
    end
  end
end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < ApplicationController
  def index
    @submissions = Submission.all
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /submissions
  # GET /submissions.json
  def index
    if user_signed_in?
      @submissions = current_user.subscribed_submissions.order("created_at desc")
    else
      @submissions = Submission.all
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @comment = Comment.new
    @community = @submission.community
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    respond_to do |format|
      unless current_user.voted_for? @submission
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "Successfully upvoted submission" }
        @submission.upvote_by current_user
      else
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "You already vote this submission" }
      end
    end
  end

  def downvote
    respond_to do |format|
      unless current_user.voted_for? @submission
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "Successfully downvoted submission" }
        @submission.downvote_by current_user
      else
        format.html { redirect_back(fallback_location: root_path) }
        format.json { head :no_content }
        format.js { flash.now[:notice] = "You already vote this submission" }
      end
    end
  end

  def unsubscribe
    user = User.find_by_unsubscribe_hash(params[:unsubscribe_hash])
    user.update_attribute(:comment_subscription, false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :body, :url, :submission_image, :submission_video, :community_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_actions.html.erb
<div class="pt-1 flex flex-wrap items-center">
  <div class="flex-1">
    <%= link_to submission_path(submission, anchor: "comments"), class: "no-underline mr-2 flex items-center" do %>
      <%= render_svg "icons/conversation", title: "Comments", styles: "fill-current text-gray-500 icon-sm hover:text-gray-600" %>
      <span class="text-sm text-gray-600 ml-2"><%= pluralize(submission.comments.count, "comment") %></span>
    <% end %>
  </div>

  <div class="flex items-center justify-end">
    <% if author_of(submission) %>

      <%= link_to edit_submission_path(submission), class: "no-underline mr-2" do %>
        <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
      <% end %>

      <%= link_to submission, method: :delete, class: "no-underline", data: { confirm: "Are you sure?" } do %>
        <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation" class="border-red-400 p-4 rounded border bg-red-100 mb-6"><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>
      <ul class="text-sm mt-2 text-red-500 pl-4">
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6 w-full lg:w-2/5">
    <div class="relative">

      <%= form.select(:community_id,
        Community.all.collect { |u| [u.name, u.id] },
        { prompt: "Choose a community" },
        { class: "select" }) %>

      <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
      </div>
    </div>
  </div>

  <hr class="border border-gray-400 my-4" />

  <div class="pb-10">
    <nav class="border-box">
      <ul id="nav-tab" class="tabs list-none flex flex-wrap justify-between">
        <li class="active w-1/3 text-center cursor-pointer" data-tab="text">
          <%= link_to "#text", class: "tab tab-first" do %>
            <%= render_svg "icons/text" %> Text
          <% end %>
        </li>

        <li class="w-1/3 text-center cursor-pointer" data-tab="image_video">
          <%= link_to "#image_video", class: "tab" do %>
            <%= render_svg "icons/image" %> Image/Video
          <% end %>
        </li>

         <li class="w-1/3 text-center cursor-pointer" data-tab="url">
          <%= link_to "#link", class: "tab tab-last" do %>
            <%= render_svg "icons/link" %> Link
          <% end %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6 text">
    <%= form.label "Text", class: "label" %>
    <%= form.rich_text_area :body, class: "input" %>
  </div>

  <div class="mb-6 url">
    <%= form.label :url, class: "label" %>
    <%= form.text_field :url, class: "input" %>
  </div>

  <div class="image_video">
    <div class="mb-6">
      <%= form.label :submission_image, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg "icons/image", styles: "fill-current text-gray-600 mr-2" %> Upload Image
        <%= form.file_field :submission_image, class: "hidden" %>
      </label>
    </div>

    <div class="mb-6">
      <%= form.label :submission_video, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg "icons/video", styles: "fill-current text-gray-600 mr-2" %> Upload Video
        <%= form.file_field :submission_video, class: "hidden" %>
      </label>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-purple" %>
  </div>
<% end %>

app/views/submissions/_guidelines.html.erb
<h3 class="font-light mb-4">Posting to Webbit</h3>
<ol class="list-reset leading p-o text-sm">
  <li class="border-b font-semibold py-1">Remember to be human</li>
  <li class="border-b font-semibold py-1">Behave like you would in real life</li>
  <li class="border-b font-semibold py-1">Look for the original source of content</li>
  <li class="border-b font-semibold py-1">Search for duplicates before posting</li>
  <li class="border-b font-semibold py-1">Read the community's rules</li>
</ol>

app/views/submissions/_posted_by.html.erb
<p class="text-gray-600 font-normal text-sm inline-block">
  Post by <%= link_to "u/#{submission.user.username}", profile_path(submission.user), class: "no-underline text-gray-600 font-normal hover:text-gray-700 hover:underline" %>
  <%= time_ago_in_words(submission.created_at) %> ago
</p>

app/views/submissions/_submission.html.erb
<div id="submission-<%= submission.id %>" class="border-b border-r border-l">
  <div class="px-2 pt-2 pb-2 flex flex-wrap items-center">
    
    <div class="submission-voting text-xs pr-2">
      <%= render "submissions/voting", submission: submission %>
    </div>

    <div>
      <%= link_to submission do %>
        <%= image_tag submission.submission_image.large.url, class: "lg:w-24 w-full max-w-full h-16 object-cover object-center" %>
      <% end if submission.submission_image.present? %>

      <%= link_to submission do %>
        <%= video_tag submission.submission_video.url, class:"lg:w-24 w-full max-w-full"  %>
      <% end if submission.submission_video.present? %>
    </div>

    <div class="flex items-start flex-1 pl-4">
      <div class="flex-1 w-full">

        <h3 class="mb-0 flex flex-wrap items-center text-base">
          <% submission_link = submission.url.present? ? submission.url : submission %>
          <%= link_to submission.title, submission_link, class: "no-underline font-semibold" %>

          <% if submission.url %>
            <span class="pl-2 text-xs font-normal font-mono text-blue-400 tracking-tighter">
              <%= link_to truncate(submission.url, length: 18), submission.url, class: "no-underline" %>
            </span>
          <% end %>
        </h3>

        <%= link_to community_path(submission.community), class: "no-underline text-gray-700 font-normal hover:text-gray-700 hover:underline text-sm inline-block" do %>
          w/<%= submission.community.name %>
        <% end %>

        <span class="mx-1 inline-block text-sm text-gray-700">•</span>

        <%= render "submissions/posted_by", submission: submission %>
        <%= render "submissions/actions", submission: submission %>

      </div>
    </div>
  </div>
</div>

app/views/submissions/_vote.js.erb
var vote = document.querySelector(
  "#submission-<%= @submission.id %> .js-votes"
);
var dynamicNotice = document.querySelector(".js-notice");
vote.innerHTML = "<%= escape_javascript(@submission.total_votes_count) %>";

dynamicNotice.innerHTML = `
  <div class="bg-white shadow rounded-lg animate fadeInUp">
    <div class="px-2 py-4 text-purple-600 text-center leading-normal font-medium font-sans flex justify-center items-center">
        <%= render_svg "icons/info", styles: "fill-current text-purple-600 icon-sm ml-4" %>
        <div class="flex-1"><%= notice %></div>
    </div>
  </div>
`;

setTimeout(function() {
  dynamicNotice.innerHTML = "";
}, 3000);

app/views/submissions/_voting.html.erb
<% if user_signed_in? %>

  <%= link_to upvote_submission_path(submission), remote: true, method: :put, class: "block text-center" do %>
    <%= render_svg "icons/up-vote", title:"upvote", styles: "fill-current text-gray-600 hover:text-purple-700 inline" %>
  <% end %>

  <span class="text-gray-700 text-center block text-sm js-votes"><%= submission.total_votes_count %></span>

  <%= link_to downvote_submission_path(submission), remote: true, method: :put, class: "block text-center" do %>
    <%= render_svg "icons/down-vote", title:"upvote", styles: "fill-current text-gray-600 hover:text-purple-700 inline" %>
  <% end %>

<% else %>

  <%= link_to new_user_session_path, class: "block text-center" do %>
    <%= render_svg "icons/up-vote", title:"upvote", styles: "fill-current text-gray-600 hover:text-purple-700 inline" %>
  <% end %>

  <span class="text-gray-700 text-center block text-sm js-votes"><%= submission.total_votes_count %></span>

  <%= link_to new_user_session_path, class: "block text-center" do %>
    <%= render_svg "icons/down-vote", title:"upvote", styles: "fill-current text-gray-600 hover:text-purple-700 inline" %>
  <% end %>

<% end %>

app/views/submissions/edit.html.erb
<%= content_for :community_label, "Editing Submission" %>

<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<% title "Submissions" %>

<%= content_for :community_label, "My Feed" %>

<% content_for :primary_content do %>

  <% if @submissions.exists? %>

    <% @submissions.each_with_index do |submission, index| %>
      <%= inject_feed_ad(index) unless active_subscriber? %>
      <%= render "submissions/submission", submission: submission %>
    <% end %>

  <% else %>
    <div class="py-10 text-center">
      <%= render_svg "icons/empty", styles: "fill-current text-gray-400 m-auto" %>
      <p class="mb-4">Wow such empty...</p>
      <%= link_to "Create a new submission", new_submission_path, class: "btn btn-purple btn-small inline-block" %>
    </div>
  <% end %>

<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <% unless user_signed_in? %>
      <%= image_tag "illustration.svg", class: "max-w-full" %>
      <h3>Explore</h3>
      <p class="text-gray-600 text-sm">Find your breaking news, sports, TV fan theories, or never-ending streams of cute animals.</p>
      <%= link_to "How Webbit works", "#", class: "btn btn-small btn-white my-2 block text-center" %>
    <% else %>
      <p class="text-gray-600 text-sm">Your personal Webbit frontpage. Come here to check in with your favorite communities.</p>
      <%= link_to 'New Submission', new_submission_path, class: "btn btn-small btn-purple my-2 block text-center" %>
      <%= link_to "New Community", new_community_path, class: "btn btn-small btn-white my-2 block text-center" %>
    <% end %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/submissions/new.html.erb
<%= content_for :community_label, "New Submission" %>
<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">New Submission</h1>

    <%= render 'form', submission: @submission %>
  </div>
<% end %>


<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-4">
    <div class="text-center my-4">
      <%= image_tag "submission.svg", class: "max-w-full w-1/2" %>
    </div>
    <%= render "guidelines" %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/submissions/show.html.erb
<% title @submission.title %>

<% content_for :community_label, title %>

<%= render "communities/community_header", community: @submission.community %>

<% content_for :primary_content do %>
  <div id="submission-<%= @submission.id %>" class="p-4 pb-6 pr-6">
    <div class="flex flex-row flex-wrap items-start justify-between">

      <div class="submission-voting text-xs pr-2">
        <%= render "voting", submission: @submission %>
      </div>

      <div class="submission-content">
        <%= render "posted_by", submission: @submission %>

        <h1 class="text-xl font-bold"><%= @submission.title %></h1>

        <div class="leading-normal text-base lg:pr-6 mb-5 border-b border-gray-200 lg:pr-6">

          <%= image_tag @submission.submission_image.large.url, class: "max-w-full my-2" if @submission.submission_image.present? %>

          <%= video_tag @submission.submission_video.url, class: "max-w-full my-2", controls: true if @submission.submission_video.present? %>

          <% if @submission.url.present? %>
            <div class="p-3 border rounded my-2 flex justify-center items-center">
              <%= render_svg "icons/link", styles: "mr-2 text-gray-600 fill-current" %>
              <%= link_to @submission.url, @submission.url, class: "lg:text-xl text-lg no-underline" %>
            </div>
          <% end %>

          <div class="py-4">
            <%= @submission.body if @submission.body %>
          </div>

        </div>
        <%= render "actions", submission: @submission %>

        <% unless user_signed_in? %>
          <p class="text-sm text-gray-600 my-2">
            <%= link_to "Login", new_user_session_path, 
            class: "link" %> or 
            <%= link_to "Sign up", new_user_registration_path, class: "link" %> to comment.
          </p>
        <% else %>
          <%= render "comments/form" %>
        <% end %>

        <div id="comments" class="mt-6 border-t border-gray-200">
          <%= render @submission.comments %>
        </div>

      </div>

    </div>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <%= render "communities/sidebar", community: @submission.community %>
<% end %>

<%= render "basic_layout" %>

<div id="edit-comment">
  <div class="modal">
    <div class="max-w-xl m-auto mt-5 bg-white p-10 pt-4 relative rounded-lg shadow-lg">
      <button class="js-close-modal absolute top-0 right-0 mr-4 mt-4">
        <%= render_svg "icons/close", title: "Close", styles: "icon-md fill-current text-gray-500" %>
      </button>
      <div class="modal-inner"></div>
    </div>
  </div>
</div>

app/views/submissions/unsubscribe.html.erb
<div class="max-w-xl my-16 m-auto p-10 rounded shadow bg-white flex items-center justify-between">
  <div class="flex-1">
    <h2 class="mt-4 text-gray-800 font-bold">Successfully unsubscribed</h2>
    <%= link_to "Return to Webbit", root_path, class: "btn btn-purple btn-small inline-block mt-4" %>
  </div>

  <%= image_tag "unsubscribe-image.svg", class: "w-64" %>
</div>

app/views/submissions/upvote.js.erb
<%= render "vote" %>