config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
      resources :users, only: [:index]
      resources :submissions, only: [:index]
      root to: "users#index"
    end
  end

  resources :communities do
    resource :subscriptions
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", :as =>
  "comment_unsubscribe"

  get :search, controller: "application"
  
  resources :submissions do
    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end
    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end
  
  devise_for :users
  resources :users, only: [:show], as: "profiles", path: "profile"
  resources :premium

  root to: "submissions#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :community
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_community, only: [:create, :destroy]

  def create
    @subscription = @community.subscriptions.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_do @community, notice: "You successfully subscribed to #{@community.name}" }
      format.js # create.js.erb
    end
  end

  def destroy
    @subscription = @community.subscriptions.where(user_id: current_user.id).first_or_create
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_do @community, notice: "You successfully unsubscribed to #{@community.name}" }
      format.js # destroy.js.erb
    end
  end

  private

    def set_community
      @community = Community.find(params[:community_id])
    end
end

app/views/subscriptions/_subscribed.js.erb
var subscribedBlock = document.getElementById('subscribed_block');
var subscribedCount = document.getElementById('subscribed_count');
subscribedBlock.innerHTML = "";
subscribedCount.innerHTML = "";
subscribedBlock.insertAdjacentHTML("beforeend", "<%= escape_javascript(render partial: "subscriptions/subscription", community: @community) %>");
subscribedCount.insertAdjacentHTML("beforeend", "<%= escape_javascript(@community.subscriptions.count.to_s) %>");

app/views/subscriptions/_subscription.html.erb
<% if user_signed_in? %>
  <% unless current_user.communities.include? @community %>
    <%= link_to "Subscribe", community_subscriptions_path(@community), method: :post, remote: true, class: "btn btn-purple btn-small w-100 block text-center" %>
  <% else %>
    <%= link_to "Unsubscribe", community_subscriptions_path(@community), method: :delete, remote: true, class: "btn btn-outline btn-small w-100 block text-center" %>
    <% end %>
<% else %>
  <%= link_to "Subscribe", new_user_session_path, class: "btn btn-purple btn-small w-100 block text-center" %>
<% end %>

app/views/subscriptions/create.js.erb
<%= render "subscribed" %>

app/views/subscriptions/destroy.js.erb
<%= render "subscribed" %>