config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
      resources :users, only: [:index]
      resources :submissions, only: [:index]
      root to: "users#index"
    end
  end

  resources :communities do
    resource :subscriptions
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", :as =>
  "comment_unsubscribe"

  get :search, controller: "application"
  
  resources :submissions do
    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end
    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end
  
  devise_for :users
  resources :users, only: [:show], as: "profiles", path: "profile"
  resources :premium

  root to: "submissions#index"
end

app/models/community.rb
class Community < ApplicationRecord
  extend FriendlyId
  before_save :format_name

  belongs_to :user
  has_many   :submissions

  has_many :subscriptions
  has_many :users, through: :subscriptions

  friendly_id :title, use: :slugged

  def format_name
    # the ! after gsub modifes the attribute.
    self.name.titleize
    self.name.gsub!(' ', '')
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)
    @community.user = current_user

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :title, :description, :sidebar)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<div class="card flex flex-wrap items-center justify-between px-4 py-2">

  <div class="flex-1">
    <%= link_to community, class: "no-underline text-gray-700" do %>
      <p class="m-0 leading-tight">
        <span class="text-xs no-underline inline-flex items-center text-gray-600">
          <%= render_svg "icons/conversation", styles: "w-3 fill-current text-gray-500 mr-1" %>
          w/<%= community.name %>
        </span>
      </p>
      <h3 class="m-0 leading-none text-base"><%= community.title %></h3>
    <% end %>
  </div>

  <div class="text-xs font-normal flex">
    <%= link_to community, class: "no-underline" do %>
      <%= render_svg "icons/view", styles: "w-4 fill-current text-gray-500", title: "View" %>
    <% end %>

    <% if author_of(community) %>
      <%= link_to edit_community_path(community), class: "no-underline ml-2" do %>
        <%= render_svg "icons/edit", styles: "w-4 fill-current text-gray-500", title: "Edit" %>
      <% end %>

      <%= link_to community, class: "no-underline ml-2", method: :delete, data: { confirm: "Are you sure?" } do %>
        <%= render_svg "icons/delete", styles: "w-4 fill-current text-gray-500", title: "Edit" %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/communities/_community_header.html.erb
<div class="bg-purple-600 text-white">
  <div class="container lg:p-10 p-4">
    <h1 class="lg:text-3xl text-lg font-bold">w/<%= community.name %></h1>
  </div>
</div>

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :sidebar, class: "label" %>
    <%= form.text_area :sidebar, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-purple btn-small" %>
  </div>
<% end %>

app/views/communities/_sidebar.html.erb
<div class="rounded">
  <div class="px-8 pt-6 pb-8">
    <div class="m-0 leading-tight flex item-center justify-between">
      <span class="text-xs no-underline inline-flex items-center text-gray-600">
        <%= render_svg "icons/conversation", styles: "w-3 fill-current text-gray-500" %>
        <span class="ml-1">w/<%= community.name %></span>
      </span>
      
      <%= link_to edit_community_path(community), class: "no-underline mr-2" do %>
        <%= render_svg "icons/edit", styles: "w-4 fill-current text-gray-500", title: "Edit" %>
      <% end if author_of(community) %>
    </div>

    <h3 class="m-0 leading-tight text-lg"><%= community.title %></h3>

    <div id="subscribed_block" class="my-6">
      <%= render "subscriptions/subscription", community: community %>
    </div>

    <div class="flex flex-wrap justify-start items-center pt-2">
      <div class="w-1/2 border-r border-gray-400">
        <p class="m-0"><%= community.submissions.count %></p>
        <p class="m-0 text-xs"><%= pluralize(community.submissions.count, 'Submission') %></p>
      </div>
      <div class="w-1/2 pl-4">
        <p id="subscribed_count" class="m-0"><%= community.subscriptions.count %></p>
        <p class="m-0 text-xs">Subscribers</p>
      </div>
    </div>

    <hr class="border-b border-gray-400" />

    <div class="text-sm mb-6"><%= community.description %></div>

    <hr class="border-b border-gray-400" />

    <div class="text-sm mb-6"><%# community.sidebar %></div>
  </div>
</div>

app/views/communities/edit.html.erb
<% content_for :community_label, "Edit Community" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 px-4">
    <h1 class="text-xl font-normal mb-6">Editing Community <%= @community.name %></h1>
    <%= render "form", community: @community %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= render_svg "community", styles: "max-w-full h-auto mb-4" %>
    <h4>Create a new community on Webbit</h4>
    <p class="text-sm italic">Each community requires the following:</p>
    <ul class="mt-1">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/index.html.erb
<% content_for :community_label, "All Communities" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Communities</h1>
    <%= render @communities %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= link_to "New Community", new_community_path if user_signed_in? %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/new.html.erb
<% content_for :community_label, "Create Community" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 px-4">
    <h1 class="text-xl font-normal mb-6">Create a Community</h1>
    <%= render "form", community: @community %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= render_svg "community", styles: "max-w-full h-auto mb-4" %>
    <h4>Create a new community on Webbit</h4>
    <p class="text-sm italic">Each community requires the following:</p>
    <ul class="mt-1">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/show.html.erb
<% content_for :community_label, "w/#{@community.name}" %>

<%= render "community_header", community: @community %>

<% content_for :primary_content do %>
  <% @community.submissions.each_with_index do |submission, index| %>
    <%= inject_feed_ad(index) unless active_subscriber? %>
    <%= render "submissions/submission", submission: submission %>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "sidebar", community: @community %>
<% end %>

<%= render "basic_layout" %>